import Link from "next/link";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import QRCode from "qrcode";
import { getStaffIdentity } from "@/lib/staff/floor-state";
import { getVenueBilling } from "@/lib/staff/billing";
import { getServiceClient } from "@/lib/supabase/service";
import { generateTagId } from "@/lib/tags/generate-ids";
import { BrandMark } from "@/components/BrandMark";
import { PrintButton } from "@/components/staff/PrintButton";
import "./qr.css";

/**
 * Printable QR codes — one per table, so a restaurant can be live
 * TONIGHT with paper while their NFC tags are in the post. Each QR
 * encodes the same /t/<tagId> URL an NFC tag would carry, so swapping
 * paper for a chip later needs no reconfiguration if the chip is
 * encoded with the same id (or simply gets its own tag row).
 *
 * Loading this page assigns a web tag to every active table that
 * doesn't have one yet. Managers and owners only; the service client
 * is used because the tags table is not exposed to staff through RLS —
 * the role check above it is the gate.
 */

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

type TableRow = { id: string; label: string };
type TagRow = { id: string; table_id: string | null; status: string };

export default async function QrPrintPage() {
  const identity = await getStaffIdentity();

  if (!identity) {
    redirect("/staff/sign-in");
  }

  if (identity.role !== "owner" && identity.role !== "manager") {
    redirect("/staff/floor");
  }

  const billing = await getVenueBilling(identity.venueId);

  if (billing.locked) {
    redirect("/staff/settings");
  }

  const service = getServiceClient();

  const [tablesResult, tagsResult] = await Promise.all([
    service
      .from("tables")
      .select("id, label")
      .eq("venue_id", identity.venueId)
      .eq("active", true)
      .order("label", { ascending: true })
      .returns<TableRow[]>(),
    service
      .from("tags")
      .select("id, table_id, status")
      .eq("venue_id", identity.venueId)
      .not("status", "in", '("lost","retired")')
      .returns<TagRow[]>(),
  ]);

  const tables = tablesResult.data ?? [];
  const tagByTable = new Map<string, string>();

  for (const tag of tagsResult.data ?? []) {
    if (tag.table_id && !tagByTable.has(tag.table_id)) {
      tagByTable.set(tag.table_id, tag.id);
    }
  }

  // Assign a web tag to every table that has none. Insert failures are
  // logged, not fatal — the page still prints what it can.
  for (const table of tables) {
    if (tagByTable.has(table.id)) {
      continue;
    }

    const tagId = generateTagId();
    const { error } = await service.from("tags").insert({
      id: tagId,
      venue_id: identity.venueId,
      table_id: table.id,
      status: "active",
      printed_ref: table.label,
      batch: "qr-web",
    });

    if (error) {
      console.error(`qr: tag insert failed for table ${table.label}`, error.message);
      continue;
    }

    tagByTable.set(table.id, tagId);
  }

  const headerList = await headers();
  const host = headerList.get("host") ?? "mytableview.com";
  const proto = headerList.get("x-forwarded-proto") ?? "https";
  const base = `${proto}://${host}/t`;

  const cards = await Promise.all(
    tables
      .filter((table) => tagByTable.has(table.id))
      .map(async (table) => {
        const url = `${base}/${tagByTable.get(table.id)}`;
        const svg = await QRCode.toString(url, {
          type: "svg",
          margin: 0,
          errorCorrectionLevel: "M",
        });
        return { table, svg };
      })
  );

  return (
    <main className="mtv-qr">
      <header className="mtv-qr-bar">
        <BrandMark className="mtv-qr-brand" />
        <div className="mtv-qr-bar-text">
          <h1>Table QR codes</h1>
          <p>
            {identity.venueName} — cut along the cards, one per table. Guests
            scan with their camera; no app needed.
          </p>
        </div>
        <div className="mtv-qr-bar-actions">
          <PrintButton />
          <Link href="/staff/floor" className="mtv-qr-back">
            Back to floor
          </Link>
        </div>
      </header>

      {cards.length === 0 ? (
        <p className="mtv-qr-empty">
          No tables yet — draw your floor in the{" "}
          <Link href="/staff/layout">layout editor</Link> first, then come back
          to print.
        </p>
      ) : (
        <section className="mtv-qr-grid">
          {cards.map(({ table, svg }) => (
            <article key={table.id} className="mtv-qr-card">
              <div
                className="mtv-qr-code"
                // Server-generated by the qrcode library from our own
                // URL — no user-controlled markup.
                dangerouslySetInnerHTML={{ __html: svg }}
              />
              <p className="mtv-qr-label">Table {table.label}</p>
              <p className="mtv-qr-hint">Scan to call your waiter</p>
            </article>
          ))}
        </section>
      )}
    </main>
  );
}
